sudo: required
os:
- linux
dist: bionic
branches:
  only:
  - master
jobs:
  include:
  - stage: build
    before_install:
    - ./.ci/ci_before_install.sh
    before_script: 
    script:
    - ./.ci/ci_test_build.sh
