name: Docs

on:
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  cancel:

    name: Cancel Previous Runs
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}

  docs:
    runs-on: ubuntu-20.04

    env:
      PUSH_TOKEN: ${{ secrets.PUSH_TOKEN }}

    steps:
      - uses: actions/checkout@v3

      - name: Install
        run: ./.ci/install.sh

      - name: Extract
        run: ./.ci/extract.sh

      - name: Push
        run: ./.ci/push.sh
